# Dashboard bookmarks links
- Documentation & Code:
    - GitHub:
        - abbr: GH
          href: https://github.com
          icon: github
    - Homepage Docs:
        - abbr: HPD
          href: https://gethomepage.dev
          icon: homepage
- External Portals:
    - Cloudflare Dash:
        - abbr: CF
          href: https://dash.cloudflare.com
          icon: cloudflare
    - Proxmox Help:
        - abbr: PVE
          href: https://pve.proxmox.com
          icon: proxmox
