# Header widgets config
- search:
    provider: duckduckgo
    target: _blank
    placeholder: Search the web...

- resources:
    cpu: true
    memory: true
    disk: /
    label: Server

- docker:
    connection: local
    label: Docker Info
    expanded: true

- datetime:
    format:
      dateStyle: long
      timeStyle: short
      hour12: false
