// Automated Third-Party License Documentation Compiler
const fs = require('fs');
const path = require('path');

const projectRoot = path.resolve(__dirname, '..');
const backendDir = path.join(projectRoot, 'dashboard', 'backend');
const packageJsonPath = path.join(backendDir, 'package.json');
const outputPath = path.join(projectRoot, 'docs', 'THIRD_PARTY_LICENSES.md');

if (!fs.existsSync(packageJsonPath)) {
  console.error(`Error: package.json not found at ${packageJsonPath}`);
  process.exit(1);
}

const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const prodDeps = Object.keys(pkg.dependencies || {}).sort();
const devDeps = Object.keys(pkg.devDependencies || {}).sort();

const header = `> [!NOTE]
> This file is automatically generated.
> Do not edit manually.
> Generated on: ${new Date().toISOString()}

# Third-Party Software Licenses Registry

This document lists the open-source dependencies used in the HomeLab OS control plane.

`;

function getPackageMetadata(dep) {
  const metaPath = path.join(backendDir, 'node_modules', dep, 'package.json');
  if (!fs.existsSync(metaPath)) {
    return { version: 'Unknown', license: 'Unknown', homepage: 'Unknown' };
  }
  try {
    const meta = JSON.parse(fs.readFileSync(metaPath, 'utf8'));
    
    // Resolve license field
    let license = meta.license || 'Unknown';
    if (typeof license === 'object') {
      license = license.type || 'Unknown';
    }
    
    // Resolve homepage / repository link
    let homepage = meta.homepage || 'Unknown';
    if (homepage === 'Unknown' && meta.repository) {
      homepage = typeof meta.repository === 'object' ? (meta.repository.url || 'Unknown') : meta.repository;
    }
    
    // Clean git+ssh prefix if any
    if (homepage !== 'Unknown') {
      homepage = homepage.replace(/^git\+/, '').replace(/\.git$/, '');
    }

    const version = meta.version || 'Unknown';

    return { version, license, homepage };
  } catch {
    return { version: 'Unknown', license: 'Unknown', homepage: 'Unknown' };
  }
}

let md = header;

// 1. Production Dependencies Table
md += `## Production Dependencies\n\n| Package | Version | License | Homepage |\n| :--- | :--- | :--- | :--- |\n`;
prodDeps.forEach(dep => {
  const meta = getPackageMetadata(dep);
  const cleanLink = meta.homepage !== 'Unknown' ? `[Link](${meta.homepage})` : 'Unknown';
  md += `| \`${dep}\` | \`${meta.version}\` | ${meta.license} | ${cleanLink} |\n`;
});

// 2. Development Dependencies Table
md += `\n## Development Dependencies\n\n| Package | Version | License | Homepage |\n| :--- | :--- | :--- | :--- |\n`;
devDeps.forEach(dep => {
  const meta = getPackageMetadata(dep);
  const cleanLink = meta.homepage !== 'Unknown' ? `[Link](${meta.homepage})` : 'Unknown';
  md += `| \`${dep}\` | \`${meta.version}\` | ${meta.license} | ${cleanLink} |\n`;
});

md += `
## Regeneration

To regenerate this file, run the following command in the project root:

\`\`\`bash
npm run generate:licenses
\`\`\`
`;

const dir = path.dirname(outputPath);
if (!fs.existsSync(dir)) {
  fs.mkdirSync(dir, { recursive: true });
}

fs.writeFileSync(outputPath, md, 'utf8');
console.log(`Successfully generated ${outputPath}`);
